### ISSUE TITLE
How to condition a transform based on an attribute value?

### ISSUE THREAD

**Issue by r3dlin3** [lithnet/umare#3]
Hi,
I'm trying to make an import attribute flow that would append a value based on another attribute.
So, for instance, let's say I have to attributes in my MA : sAMAccountName and employeeType. I want to compute the mail by concatenating sAMAccountName + emailSuffix. The emailSuffix depends on the employeeType (@internal for internal users, @external for external users).

So far, for concatenating value, I use a regexp for "$" which I replace by "@adomain.com". 
Is there a way to go around this with a lookup or something?
I do not know if the syntax would allow to work on several attributes, apply a transform on one attribute and use the result with another attribtute on the same attribute flow.

**Comment by ryannewington** [comment]
Hi @r3dlin3,

This isn't something you can do easily in UMARE at the moment. I've got conditional flows planned for a later release, but I dont have an expected date when this will be available.

[ACMA](https://github.com/lithnet/acma) can do this with ease. It's designed for creating new information, which in your case is the email address. UMARE is more for transforming existing information, rather than creating new information. For example, transforming a date from AD filetime to fim portal date string. The 'information' (the date that being represented) hasn't changed, it's just presented in a different format. The two tools are quite powerful when used together this way. I've for a [video](https://www.youtube.com/watch?v=Lvuqvvx-DNA) outlining how we did this in our environment if you care to find out more.

Hope that helps

Ryan

**Comment by r3dlin3** [comment]
First of all, kudos for all this great work on UMARE et ACMA and for this very inspiring video.
I'm already using UMARE and FIM.MRE.
I'll give a try to ACMA. 

Thank you
